### PR TITLE
use `stdbool` in generated bindings

### LINKED ISSUE #1: IsKeyDown (and IsKeyUp) always #t on Ubuntu Install
I do not know the extent of this issue or if it is user error (probably), but I was trying to adapt an easy example from https://www.raylib.com/examples.html

I tried:
```
(module+ main
  (require raylib/2d/unsafe)

  (InitWindow 800 450 "raylib [core] example - basic window")
  (let loop ()
    (when (not (WindowShouldClose))
      (DrawText (format "~v\n" (IsKeyDown KEY_RIGHT)) 200 200 20 LIGHTGRAY)
      (ClearBackground RAYWHITE)
      (EndDrawing)
      (loop)))

  (CloseWindow))
```
And, regardless of whether or not the right arrow key is pressed, it will always produce `#t`
This is the same for other keys and for IsKeyUp.
I am on linux (ubuntu) using Racket 8.6 (and confirmed in 8.8). I installed using raco as recommended and the example in the repo works as expected.

On windows using Racket 8.7, the example behaves as you would expect it to: #f by default until you press right.

Any insight is appreciated :) Hopefully this was detailed enough, but I'm happy to provide more information.

### PR DESCRIPTION
**Pull request by lygaret**
should fix #1 - see that for bug details

* added `_stdbool` as the FFI type mapping for `bool` from raylib
* regenerated code with:
  ```
  ~/code/racket/raylib> racket -S .. x.rkt --all 4.0.0
  ```

### CODE REVIEW

**Comment by lygaret** [comment]
It doesn't look like there's `_bool` types in raymath at all, so I didn't touch any of that.

**Comment by lygaret** [comment]
With these changes, this example works:

```racket
  (InitWindow 800 450 "raylib [core] example - basic window")
  (let loop ()
    (when (not (WindowShouldClose))
      (DrawText (format "~v\n" (IsKeyDown KEY_RIGHT)) 200 200 20 LIGHTGRAY)
      (ClearBackground RAYWHITE)
      (EndDrawing)
      (loop)))
  (CloseWindow)
```

**Comment by eutro** [comment]
Thank you for this.

**Comment by mpahrens** [comment]
Here is a belated thank you!

**Pull request merged**
